[package]
name = "yumu"
description = "Yumu Minecraft launcher command line"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
heartwood.workspace = true
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
dev-offline = ["heartwood/dev-offline"]

[lints]
workspace = true
